export type CapBucket = "Mega" | "Large" | "Mid" | "Small" | "Micro";

export type HolderType = "Marquee Investor" | "Promoter / Business Family";

export interface StockResearchHolding {
  symbol: string;
  company: string;
  holder: string;
  holderType: HolderType;
  stakePct: number | null;
  marketCapCr: number;
  capBucket: CapBucket;
  sector: string;
  coreBusiness: string;
  monopoly: boolean;
  monopolyNote: string;
}

export function capBucket(marketCapCr: number): CapBucket {
  if (marketCapCr >= 500_000) return "Mega";
  if (marketCapCr >= 50_000) return "Large";
  if (marketCapCr >= 20_000) return "Mid";
  if (marketCapCr >= 5_000) return "Small";
  return "Micro";
}

// Curated, manually-maintained snapshot. Figures are approximate and drawn from
// publicly disclosed BSE/NSE shareholding patterns and promoter filings — not a
// live feed. Refresh periodically; do not treat as investment advice.
export const STOCK_RESEARCH_DATA: StockResearchHolding[] = [
  {
    symbol: "TITAN",
    company: "Titan Company Ltd",
    holder: "RARE Enterprises (Rakesh Jhunjhunwala family / Rekha Jhunjhunwala)",
    holderType: "Marquee Investor",
    stakePct: 5.1,
    marketCapCr: 305000,
    capBucket: capBucket(305000),
    sector: "Consumer Discretionary — Jewellery & Watches",
    coreBusiness: "Branded jewellery (Tanishq), watches (Titan, Fastrack), eyewear",
    monopoly: false,
    monopolyNote: "Dominant organised-jewellery player but competes with Kalyan, Malabar, PC Jeweller",
  },
  {
    symbol: "TATAMOTORS",
    company: "Tata Motors Ltd",
    holder: "RARE Enterprises (Rekha Jhunjhunwala)",
    holderType: "Marquee Investor",
    stakePct: 0.4,
    marketCapCr: 260000,
    capBucket: capBucket(260000),
    sector: "Auto — Commercial & Passenger Vehicles",
    coreBusiness: "Trucks, buses, passenger cars, JLR luxury brands",
    monopoly: false,
    monopolyNote: "Large CV market share but competitive PV/CV space",
  },
  {
    symbol: "DMART",
    company: "Avenue Supermarts Ltd (DMart)",
    holder: "Radhakishan Damani (RK Damani family)",
    holderType: "Promoter / Business Family",
    stakePct: 62.2,
    marketCapCr: 240000,
    capBucket: capBucket(240000),
    sector: "Retail — Organised Grocery/Value Retail",
    coreBusiness: "Supermarket chain, everyday-value grocery & general merchandise",
    monopoly: false,
    monopolyNote: "Regional density leader in Maharashtra/Gujarat; competes with Reliance Retail, Big Bazaar successors",
  },
  {
    symbol: "VST INDUSTRIES",
    company: "VST Industries Ltd",
    holder: "Radhakishan Damani",
    holderType: "Marquee Investor",
    stakePct: 3.5,
    marketCapCr: 8500,
    capBucket: capBucket(8500),
    sector: "FMCG — Tobacco",
    coreBusiness: "Cigarette manufacturing",
    monopoly: false,
    monopolyNote: "Distant #3 behind ITC and Godfrey Phillips in Indian cigarettes",
  },
  {
    symbol: "VIPIND",
    company: "VIP Industries Ltd",
    holder: "Radhakishan Damani",
    holderType: "Marquee Investor",
    stakePct: 4.9,
    marketCapCr: 6800,
    capBucket: capBucket(6800),
    sector: "Consumer Discretionary — Luggage",
    coreBusiness: "Luggage & travel bags (VIP, Skybags, Carlton, Caprese)",
    monopoly: false,
    monopolyNote: "Largest organised luggage maker in India but faces Safari, Samsonite competition",
  },
  {
    symbol: "CRISIL",
    company: "CRISIL Ltd",
    holder: "S&P Global (majority) / tracked as promoter-controlled",
    holderType: "Promoter / Business Family",
    stakePct: 66.7,
    marketCapCr: 34000,
    capBucket: capBucket(34000),
    sector: "Financial Services — Credit Rating & Research",
    coreBusiness: "Credit ratings, analytics, research, risk & policy advisory",
    monopoly: false,
    monopolyNote: "Top rating agency alongside ICRA and CARE; not a sole monopoly",
  },
  {
    symbol: "ATULAUTO",
    company: "Atul Auto Ltd",
    holder: "Vijay Kedia",
    holderType: "Marquee Investor",
    stakePct: 2.1,
    marketCapCr: 1400,
    capBucket: capBucket(1400),
    sector: "Auto — Three-Wheelers",
    coreBusiness: "Three-wheeler passenger & cargo vehicles",
    monopoly: false,
    monopolyNote: "Niche player behind Bajaj Auto and Piaggio in 3-wheeler segment",
  },
  {
    symbol: "PRECAM",
    company: "Precision Camshafts Ltd",
    holder: "Vijay Kedia",
    holderType: "Marquee Investor",
    stakePct: 5.0,
    marketCapCr: 1300,
    capBucket: capBucket(1300),
    sector: "Auto Ancillary — Precision Components",
    coreBusiness: "Camshaft castings & machined components for auto OEMs",
    monopoly: false,
    monopolyNote: "One of few dedicated camshaft-casting specialists globally, but small scale",
  },
  {
    symbol: "TEJASNET",
    company: "Tejas Networks Ltd",
    holder: "Ashish Kacholia",
    holderType: "Marquee Investor",
    stakePct: 1.8,
    marketCapCr: 9000,
    capBucket: capBucket(9000),
    sector: "Telecom Equipment",
    coreBusiness: "Optical & data networking products, telecom hardware (Tata group-backed)",
    monopoly: false,
    monopolyNote: "Key domestic telecom-gear vendor under PLI push, competes with global majors",
  },
  {
    symbol: "SHALBY",
    company: "Shalby Ltd",
    holder: "Ashish Kacholia",
    holderType: "Marquee Investor",
    stakePct: 2.4,
    marketCapCr: 2200,
    capBucket: capBucket(2200),
    sector: "Healthcare — Hospitals",
    coreBusiness: "Multi-specialty hospital chain, orthopaedic implants",
    monopoly: false,
    monopolyNote: "Regional hospital chain; fragmented industry with many private players",
  },
  {
    symbol: "PONDYOXIDE",
    company: "Pondy Oxides & Chemicals Ltd",
    holder: "Dolly Khanna",
    holderType: "Marquee Investor",
    stakePct: 1.5,
    marketCapCr: 1600,
    capBucket: capBucket(1600),
    sector: "Metals — Lead Recycling",
    coreBusiness: "Secondary lead smelting, lead alloys, oxides",
    monopoly: false,
    monopolyNote: "Among the larger organised lead-recyclers domestically, not a monopoly",
  },
  {
    symbol: "GPTINFRA",
    company: "GPT Infraprojects Ltd",
    holder: "Dolly Khanna",
    holderType: "Marquee Investor",
    stakePct: 1.2,
    marketCapCr: 900,
    capBucket: capBucket(900),
    sector: "Infrastructure — Railway EPC",
    coreBusiness: "Railway bridges, sleepers, EPC construction",
    monopoly: false,
    monopolyNote: "Niche railway-infra contractor competing with larger EPC players",
  },
  {
    symbol: "SUNPHARMA",
    company: "Sun Pharmaceutical Industries Ltd",
    holder: "Dilip Shanghvi & family (promoter)",
    holderType: "Promoter / Business Family",
    stakePct: 54.5,
    marketCapCr: 465000,
    capBucket: capBucket(465000),
    sector: "Pharmaceuticals",
    coreBusiness: "Generic & specialty formulations, largest Indian pharma company",
    monopoly: false,
    monopolyNote: "Market leader by revenue but operates in a fragmented, competitive generics industry",
  },
  {
    symbol: "RELIANCE",
    company: "Reliance Industries Ltd",
    holder: "Mukesh Ambani & family (promoter, Reliance Industrial Investments)",
    holderType: "Promoter / Business Family",
    stakePct: 50.3,
    marketCapCr: 1950000,
    capBucket: capBucket(1950000),
    sector: "Conglomerate — Energy, Retail, Telecom",
    coreBusiness: "Oil-to-chemicals refining, Jio telecom, Reliance Retail",
    monopoly: false,
    monopolyNote: "Dominant scale in telecom (Jio) and retail but faces Airtel/Vi and Amazon/Flipkart-DMart competition",
  },
  {
    symbol: "ADANIENT",
    company: "Adani Enterprises Ltd",
    holder: "Gautam Adani & family (promoter, S B Adani Family Trust)",
    holderType: "Promoter / Business Family",
    stakePct: 70.0,
    marketCapCr: 365000,
    capBucket: capBucket(365000),
    sector: "Conglomerate — Infrastructure, Ports, Energy, Mining",
    coreBusiness: "Incubator entity for ports, airports, green hydrogen, mining, data centres",
    monopoly: false,
    monopolyNote: "Leads in several infra sub-segments (ports via Adani Ports) but not a legal monopoly in any regulated market",
  },
  {
    symbol: "ADANIPORTS",
    company: "Adani Ports & SEZ Ltd",
    holder: "Gautam Adani & family (promoter)",
    holderType: "Promoter / Business Family",
    stakePct: 65.9,
    marketCapCr: 285000,
    capBucket: capBucket(285000),
    sector: "Infrastructure — Ports & Logistics",
    coreBusiness: "India's largest private port operator and integrated logistics",
    monopoly: false,
    monopolyNote: "Largest private-port cargo share in India, but public ports (JNPT, Cochin) and other private terminals compete",
  },
  {
    symbol: "DLF",
    company: "DLF Ltd",
    holder: "K.P. Singh & family (promoter)",
    holderType: "Promoter / Business Family",
    stakePct: 74.9,
    marketCapCr: 210000,
    capBucket: capBucket(210000),
    sector: "Real Estate",
    coreBusiness: "Residential & commercial real estate development, primarily NCR",
    monopoly: false,
    monopolyNote: "Largest listed developer by market cap but real estate remains highly fragmented and local",
  },
  {
    symbol: "BAJFINANCE",
    company: "Bajaj Finance Ltd",
    holder: "Bajaj family (Bajaj Finserv/Bajaj Holdings, promoter group)",
    holderType: "Promoter / Business Family",
    stakePct: 55.9,
    marketCapCr: 435000,
    capBucket: capBucket(435000),
    sector: "Financial Services — NBFC",
    coreBusiness: "Consumer & SME lending, EMI cards, deposits",
    monopoly: false,
    monopolyNote: "Largest listed NBFC by market cap; competes with banks and other NBFCs",
  },
  {
    symbol: "HAVELLS",
    company: "Havells India Ltd",
    holder: "Gupta family (Anil Rai Gupta, promoter)",
    holderType: "Promoter / Business Family",
    stakePct: 59.5,
    marketCapCr: 100000,
    capBucket: capBucket(100000),
    sector: "Consumer Electricals",
    coreBusiness: "Switchgear, cables, fans, lighting, home appliances (Lloyd AC)",
    monopoly: false,
    monopolyNote: "Strong brand share in electricals but competes with Polycab, Crompton, Orient",
  },
];

export const HOLDER_TYPES: HolderType[] = ["Marquee Investor", "Promoter / Business Family"];
export const CAP_BUCKETS: CapBucket[] = ["Mega", "Large", "Mid", "Small", "Micro"];
