import type { StrategyDefinition, RegimeDefinition } from './types'

export const STRATEGIES: StrategyDefinition[] = [
  {
    id: 'S1',
    name: 'Opening Range Breakout',
    timeframe: 'intraday',
    type: 'Foundation',
    allowedRegimes: ['TrendingBull', 'TrendingBear'],
    description: 'First 30-min range breakout (09:15–09:45) with 1.5× volume confirmation. SL at opposite range extreme.',
    minSLPct: 0.3,
    minRR: 2.0,
    targetWinRate: 0.56,
    instruments: ['FUTURE', 'CE', 'PE'],
  },
  {
    id: 'S2',
    name: 'VWAP Mean Reversion',
    timeframe: 'intraday',
    type: 'Foundation',
    allowedRegimes: ['TrendingBull', 'TrendingBear', 'Ranging'],
    description: 'Price deviation from VWAP triggers mean-reversion entry. RSI confirmation at extremes.',
    minSLPct: 0.25,
    minRR: 2.0,
    targetWinRate: 0.55,
    instruments: ['FUTURE', 'CE', 'PE'],
  },
  {
    id: 'S3',
    name: 'IV Crush',
    timeframe: 'intraday',
    type: 'Foundation',
    allowedRegimes: ['EventRisk'],
    description: 'Sells options post-event to capture IV crush. Targets inflated IV that collapses after news.',
    minSLPct: 0.0,
    minRR: 0.0,
    targetWinRate: 0.65,
    instruments: ['CE', 'PE'],
  },
  {
    id: 'S4',
    name: 'PCR Reversal',
    timeframe: 'intraday',
    type: 'Foundation',
    allowedRegimes: ['TrendingBull', 'TrendingBear'],
    description: 'Put-Call Ratio extreme readings signal sentiment reversals. PCR > 1.3 = bullish, < 0.7 = bearish.',
    minSLPct: 0.3,
    minRR: 2.0,
    targetWinRate: 0.52,
    instruments: ['FUTURE', 'CE', 'PE'],
  },
  {
    id: 'S5',
    name: 'Max Pain Target',
    timeframe: 'swing',
    type: 'Foundation',
    allowedRegimes: ['TrendingBull', 'TrendingBear', 'Ranging', 'HighVol'],
    description: 'Trades toward the max-pain strike as expiry approaches. OI-weighted gravity pull on index.',
    minSLPct: 0.25,
    minRR: 2.0,
    targetWinRate: 0.54,
    instruments: ['FUTURE'],
  },
  {
    id: 'S6',
    name: 'OI Buildup Trend',
    timeframe: 'intraday',
    type: 'Foundation',
    allowedRegimes: ['TrendingBull', 'TrendingBear'],
    description: 'Open interest buildup in specific strikes confirms directional bias for trend continuation.',
    minSLPct: 0.3,
    minRR: 2.0,
    targetWinRate: 0.55,
    instruments: ['FUTURE', 'CE', 'PE'],
  },
  {
    id: 'S7',
    name: 'Gap Fill',
    timeframe: 'swing',
    type: 'Foundation',
    allowedRegimes: ['TrendingBull', 'TrendingBear', 'Ranging', 'HighVol', 'EventRisk'],
    description: 'Overnight gap fills historically occur 70% of the time. Fades gap direction toward prior close.',
    minSLPct: 0.25,
    minRR: 2.0,
    targetWinRate: 0.58,
    instruments: ['FUTURE'],
  },
  {
    id: 'S8',
    name: 'EMA Ribbon Trend',
    timeframe: 'intraday',
    type: 'Foundation',
    allowedRegimes: ['TrendingBull', 'TrendingBear'],
    description: 'Multi-EMA ribbon alignment (EMA9/21/50) confirms trend. Entry on pullback to ribbon.',
    minSLPct: 0.3,
    minRR: 2.0,
    targetWinRate: 0.55,
    instruments: ['FUTURE', 'CE', 'PE'],
  },
  {
    id: 'S9',
    name: 'Event Vol',
    timeframe: 'swing',
    type: 'Foundation',
    allowedRegimes: ['EventRisk'],
    description: 'Buys straddles pre-event to capture IV expansion and directional move.',
    minSLPct: 0.0,
    minRR: 0.0,
    targetWinRate: 0.50,
    instruments: ['STRANGLE'],
  },
  {
    id: 'S10',
    name: 'Tick Scalp Bid/Ask Compression',
    timeframe: 'scalping',
    type: 'Scalping',
    allowedRegimes: ['TrendingBull', 'TrendingBear', 'Ranging'],
    description: 'Spread < 0.5×ATR1m with 3-bar order flow confirmation. Window 09:15–14:45.',
    minSLPct: 0.2,
    minRR: 2.0,
    targetWinRate: 0.60,
    instruments: ['FUTURE'],
  },
  {
    id: 'S11',
    name: 'Pullback Scalp VWAP Micro',
    timeframe: 'scalping',
    type: 'Scalping',
    allowedRegimes: ['TrendingBull', 'TrendingBear'],
    description: 'Price within ±0.5×ATR of 5m VWAP + RSI extreme + volume spike >1.5×. Window 09:30–14:30.',
    minSLPct: 0.25,
    minRR: 2.0,
    targetWinRate: 0.58,
    instruments: ['FUTURE'],
  },
  {
    id: 'S12',
    name: 'Volume Spike Scalp Order Flow',
    timeframe: 'scalping',
    type: 'Scalping',
    allowedRegimes: ['TrendingBull', 'TrendingBear', 'Ranging'],
    description: 'Volume >2× 20-bar avg + 2/3 confirmation bars + body >60% of range. Window 09:15–14:30.',
    minSLPct: 0.2,
    minRR: 2.0,
    targetWinRate: 0.52,
    instruments: ['FUTURE'],
  },
  {
    id: 'S13',
    name: 'EMA Ribbon Scalp Fast',
    timeframe: 'scalping',
    type: 'Scalping',
    allowedRegimes: ['TrendingBull', 'TrendingBear'],
    description: 'EMA3 > EMA5 > EMA9 alignment + MACD histogram + price within 0.5×ATR of EMA3. Window 09:30–14:45.',
    minSLPct: 0.25,
    minRR: 2.0,
    targetWinRate: 0.55,
    instruments: ['FUTURE'],
  },
  {
    id: 'S14',
    name: 'Breakout Scalp Support/Resistance',
    timeframe: 'scalping',
    type: 'Scalping',
    allowedRegimes: ['TrendingBull', 'TrendingBear'],
    description: 'Opening range (09:15–09:45) breakout post-09:45 with 1.5× volume. Active until 13:00.',
    minSLPct: 0.3,
    minRR: 2.0,
    targetWinRate: 0.56,
    instruments: ['FUTURE'],
  },
  {
    id: 'S15',
    name: 'RSI Divergence Scalp',
    timeframe: 'scalping',
    type: 'Scalping',
    allowedRegimes: ['TrendingBull', 'TrendingBear'],
    description: 'Bull: price lower-low + RSI higher-low + RSI<35. Bear: price higher-high + RSI lower-high + RSI>65. Window 09:30–13:30.',
    minSLPct: 0.3,
    minRR: 2.0,
    targetWinRate: 0.50,
    instruments: ['FUTURE'],
  },
  {
    id: 'S16',
    name: 'ATR Breakout Scalp Volatility',
    timeframe: 'scalping',
    type: 'Scalping',
    allowedRegimes: ['HighVol'],
    description: 'ONLY in HighVol regime. 5m candle >1.5×ATR5 expansion. Window 09:15–14:45.',
    minSLPct: 0.25,
    minRR: 2.0,
    targetWinRate: 0.54,
    instruments: ['FUTURE'],
  },
  {
    id: 'S17',
    name: 'Opening Range Breakout Intraday',
    timeframe: 'intraday',
    type: 'Intraday',
    allowedRegimes: ['TrendingBull', 'TrendingBear'],
    description: 'Classic ORB on 15m timeframe with volume and ADX confirmation. Holds for 45 min–4h.',
    minSLPct: 0.3,
    minRR: 2.0,
    targetWinRate: 0.56,
    instruments: ['FUTURE', 'CE', 'PE'],
  },
  {
    id: 'S18',
    name: 'VWAP Mean Reversion Straddle',
    timeframe: 'intraday',
    type: 'Intraday',
    allowedRegimes: ['TrendingBull', 'TrendingBear', 'Ranging'],
    description: 'Straddle entered near VWAP when price oscillates. Benefits from both-direction moves.',
    minSLPct: 0.0,
    minRR: 0.0,
    targetWinRate: 0.55,
    instruments: ['STRANGLE'],
  },
  {
    id: 'S19',
    name: 'ADX Trend Filter Breakouts',
    timeframe: 'intraday',
    type: 'Intraday',
    allowedRegimes: ['TrendingBull', 'TrendingBear'],
    description: 'ADX > 25 confirms strong trend. Enters on 15m breakout of prior high/low with trend direction.',
    minSLPct: 0.3,
    minRR: 2.0,
    targetWinRate: 0.57,
    instruments: ['FUTURE', 'CE', 'PE'],
  },
  {
    id: 'S20',
    name: 'Fibonacci Retracement Intraday',
    timeframe: 'intraday',
    type: 'Intraday',
    allowedRegimes: ['TrendingBull', 'TrendingBear'],
    description: 'Swing high/low identifies Fib levels. Entry at 38.2% or 61.8% retracement with RSI confirmation.',
    minSLPct: 0.3,
    minRR: 2.0,
    targetWinRate: 0.55,
    instruments: ['FUTURE', 'CE', 'PE'],
  },
  {
    id: 'S21',
    name: 'Bollinger Band Squeeze Breakout',
    timeframe: 'intraday',
    type: 'Intraday',
    allowedRegimes: ['TrendingBull', 'TrendingBear', 'Ranging'],
    description: 'BB bandwidth squeeze followed by expansion. Enters on breakout bar with volume confirmation.',
    minSLPct: 0.3,
    minRR: 2.0,
    targetWinRate: 0.54,
    instruments: ['FUTURE', 'CE', 'PE'],
  },
  {
    id: 'S22',
    name: 'News Event Vol Fade',
    timeframe: 'intraday',
    type: 'Intraday',
    allowedRegimes: ['EventRisk'],
    description: 'Sells options 15 min post-event announcement. Captures IV crush on 15m–1h timeframe.',
    minSLPct: 0.0,
    minRR: 0.0,
    targetWinRate: 0.62,
    instruments: ['CE', 'PE'],
  },
  {
    id: 'S23',
    name: 'Weekly Options Theta Decay Strangle',
    timeframe: 'swing',
    type: 'Swing',
    allowedRegimes: ['Ranging'],
    description: 'Monday entry only. Sells weekly strangle to collect theta. Exits Friday or at 50% profit.',
    minSLPct: 0.0,
    minRR: 0.0,
    targetWinRate: 0.68,
    instruments: ['STRANGLE'],
  },
  {
    id: 'S24',
    name: 'Momentum Breakout Swing',
    timeframe: 'swing',
    type: 'Swing',
    allowedRegimes: ['TrendingBull', 'TrendingBear'],
    description: 'Daily close above 20-day high with volume. Holds for 1–5 days targeting 3–4× R:R.',
    minSLPct: 0.25,
    minRR: 2.0,
    targetWinRate: 0.48,
    instruments: ['FUTURE'],
  },
  {
    id: 'S25',
    name: 'Mean Reversion RSI Oversold Swing',
    timeframe: 'swing',
    type: 'Swing',
    allowedRegimes: ['TrendingBull', 'TrendingBear', 'Ranging'],
    description: 'Daily RSI < 30 (long) or > 70 (short) at support/resistance. Holds 2–7 days.',
    minSLPct: 0.25,
    minRR: 2.0,
    targetWinRate: 0.52,
    instruments: ['FUTURE', 'CE', 'PE'],
  },
  {
    id: 'S26',
    name: 'Sector Rotation Nifty Rebalance',
    timeframe: 'swing',
    type: 'Swing',
    allowedRegimes: ['TrendingBull'],
    description: 'Sector FII flow rebalancing signals Nifty direction. ONLY in bull regime. Monthly bias.',
    minSLPct: 0.25,
    minRR: 2.0,
    targetWinRate: 0.55,
    instruments: ['FUTURE'],
  },
  {
    id: 'S27',
    name: 'Gap Up/Down Fade Options',
    timeframe: 'swing',
    type: 'Swing',
    allowedRegimes: ['TrendingBull', 'TrendingBear'],
    description: 'Gap > 0.5% at open: fade the gap direction. Buys ATM options for leverage. 70% fill historically.',
    minSLPct: 0.0,
    minRR: 0.0,
    targetWinRate: 0.58,
    instruments: ['CE', 'PE'],
  },
  {
    id: 'S28',
    name: 'Earnings Straddle IV Play',
    timeframe: 'swing',
    type: 'Swing',
    allowedRegimes: ['EventRisk'],
    description: 'Buys straddle 2 days before earnings. Exits day of announcement. Captures IV expansion.',
    minSLPct: 0.0,
    minRR: 0.0,
    targetWinRate: 0.50,
    instruments: ['STRANGLE'],
  },
  {
    id: 'S29',
    name: 'Index Futures Positional Trend',
    timeframe: 'swing',
    type: 'Swing',
    allowedRegimes: ['TrendingBull', 'TrendingBear'],
    description: 'Weekly trend following on index futures. 4:1 R:R target. Holds 5–15 days. ADX > 30 required.',
    minSLPct: 0.25,
    minRR: 4.0,
    targetWinRate: 0.48,
    instruments: ['FUTURE'],
  },
]

export const REGIMES: RegimeDefinition[] = [
  {
    code: 'TrendingBull',
    label: 'Trending Bull',
    color: '#00C087',
    sizeMult: 1.0,
    description: 'Strong uptrend — EMA aligned up, ADX > 25',
  },
  {
    code: 'TrendingBear',
    label: 'Trending Bear',
    color: '#FF5733',
    sizeMult: 1.0,
    description: 'Strong downtrend — EMA aligned down, ADX > 25',
  },
  {
    code: 'Ranging',
    label: 'Ranging',
    color: '#4285F4',
    sizeMult: 0.7,
    description: 'Sideways market — ADX < 20, price oscillating around VWAP',
  },
  {
    code: 'HighVol',
    label: 'High Vol',
    color: '#F5A623',
    sizeMult: 0.5,
    description: 'VIX elevated (> 20) — only S16 ATR Breakout active',
  },
  {
    code: 'EventRisk',
    label: 'Event Risk',
    color: '#F5A623',
    sizeMult: 0.3,
    description: 'Pre/post-event window — RBI, Fed, earnings blackout',
  },
  {
    code: 'ExpiryDay',
    label: 'Expiry Day',
    color: '#9F7AEA',
    sizeMult: 0.0,
    description: 'NSE weekly/monthly expiry — ALL new entries blocked',
  },
]

export const LOT_SIZES: Record<string, number> = {
  NIFTY: 75,
  BANKNIFTY: 30,
}

export const STRATEGY_MAP: Record<string, string> = Object.fromEntries(
  STRATEGIES.map((s) => [s.id, s.name])
)

export const TIMEFRAME_COLORS: Record<string, string> = {
  scalping: '#4285F4',
  intraday: '#00C087',
  swing: '#F5A623',
}

export const STATUS_COLORS: Record<string, string> = {
  ACTIVE: '#00C087',
  BLOCKED: '#8B949E',
  INSUFFICIENT_DATA: '#F5A623',
  DEMOTED: '#FF5733',
}

export const REGULATORY_FLAGS = [
  {
    name: 'Nifty Lot Size',
    value: '75 units',
    note: 'VERIFY: NSE F&O contract spec circular — changes periodically',
    circular: 'NSE/FAOP circular',
  },
  {
    name: 'BankNifty Lot Size',
    value: '30 units',
    note: 'VERIFY: NSE F&O contract spec circular',
    circular: 'NSE/FAOP circular',
  },
  {
    name: 'STT on Options Sell',
    value: '0.1% on premium',
    note: 'VERIFY: Finance Act / CBDT circular',
    circular: 'Finance Act Section 111A',
  },
  {
    name: 'Nifty Weekly Expiry',
    value: 'Tuesday',
    note: 'VERIFY: NSE circular — day may change',
    circular: 'NSE circular No. NSE/FAOP',
  },
  {
    name: 'BankNifty Weekly Expiry',
    value: 'DISCONTINUED (Nov 2024)',
    note: 'Monthly expiry only — was Wednesday',
    circular: 'NSE circular Nov 2024',
  },
  {
    name: 'Exchange Transaction Charge',
    value: '0.05% (futures) / 0.05% (options)',
    note: 'VERIFY: NSE/BSE rate card',
    circular: 'NSE rate card',
  },
]
